name: CI Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: DVC pull
        run: dvc pull -r gcsremote
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Run Pytest
        run: pytest tests/
      - name: Run CML Report
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "## IRIS Dev Branch Test Report" > report.md
          pytest tests/ --tb=short | tee -a report.md
          cml comment create report.md

